print("O Daniel é legal!")
print("O Celso também é legal!")
print("Faltou o Felipe, ele também é legal")
print("Por fim o MAIS LEGAL, Marlon!")
print("Complicado né, atrasar depois do intervalo!")
print("Obaa, a galera voltou!")
